### ISSUE TITLE
[FEAT] Add possibility to stream camera

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-PHAL-plugin-homeassistant#39]
It would be nice to use the camera of the MarkII or DevKit as an option with Homeassistant. I.e. "start security camera" would stream to home assistant like motioneye

**Comment by mikejgray** [comment]
@denics This is something that we'd need to also set up on https://github.com/mikejgray/ovos-home-assistant-integration in order to make the MarkII/DevKit expose a `camera` entity. Would you mind moving this issue over there, please?
