### ISSUE TITLE
Incompatability with latest ovos-dinkum-listener

### ISSUE THREAD

**Issue by Ramblurr** [OpenVoiceOS/ovos-PHAL-plugin-homeassistant#42]
1. ovos-PHAL-plugin-homeassistant requires [ovos-PHAL-plugin-oauth~=0.0.1](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant/blob/dev/requirements.txt#L7)
2. ovos-PHAL-plugin-oauth requires [ovos-backend-client~=0.0.6](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-oauth/blob/dev/requirements.txt#L1)
3. ovos-dinkum-listener requires [ovos-backend-client>=0.1.0a7](https://github.com/OpenVoiceOS/ovos-dinkum-listener/blob/dev/requirements/requirements.txt#L1) (as of [1 month ago](https://github.com/OpenVoiceOS/ovos-dinkum-listener/commit/58625f8f81d3154a7d4d4f52369205e1cccdcd24))

2 and 3 are incompatible.

Not sure what the best solution is here... any ideas?

**Comment by NeonDaniel** [comment]
I see `ovos-phal-plugin-oauth` spec `ovos-backend-client>=0.0.6`, so I don't think that would cause a conflict.

1 and 3 are incompatible still though

**Comment by NeonDaniel** [comment]
This was probably related to ovos-utils 0.1 which is supported in the latest alpha release; is this still an issue?

**Comment by mikejgray** [comment]
I've run several systems on ovos-utils 0.1.0 without an issue. I think this was resolved by #43.
